"""empty message

Revision ID: 5930870a26b
Revises: None
Create Date: 2015-03-18 10:00:33.016172

"""

# revision identifiers, used by Alembic.
revision = '5930870a26b'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('charity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bank_token', sa.String(length=60), nullable=True),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('token_id', sa.String(length=60), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('customer')
    op.drop_table('charity')
    ### end Alembic commands ###
